name: "[Dispatch] Create Plugin Template"

on:
  workflow_dispatch:
    inputs:
      resource_type:
        description: 'plugin type ex) (inventory.Collector, cost-analysis.DataSource, monitoring.Webhook, notification.Notification ...)'
        required: true
        default: 'inventory.Collector'
      core-version:
        description: 'core version'
        required: true
        default: '2.0'
env:
  REPO: forest-extension/actions
  WORKFLOW_NAME: dispatch_apply_plugin_template.yaml

jobs:
  pull_plugin_template:
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: request workflows
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: ${{ env.REPO }}
          workflow: ${{ env.WORKFLOW_NAME }}
          inputs: '{"dest" : "${{ github.event.repository.name }}"}'